management:
  endpoints:
    web:
      exposure:
        include: health,info,env
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
security:
  jwt:
    issuer: "crediya-auth"
    secret: "${JWT_SECRET:mysuperlongsecretkeyforhs256alg!!!123456}"
    ttl-seconds: 7200
jwt:
  json-exp-roles: "/roles"
spring:
  r2dbc:
    #url: r2dbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:crediya_soli}
    url: r2dbc:postgresql://${DB_HOST:crediya-postgres-soli}:${DB_PORT:5432}/${DB_NAME:crediya_soli}
    username: ${DB_USER:crediya}
    password: ${DB_PASSWORD:crediya}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ""
          client-id: ""
ms-auth:
  base-url: http://localhost:8080/api/v1
# Propiedades usadas por el driven-adapter R2DBC del scaffold
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    database: ${DB_NAME:crediya_soli}
    schema: ${DB_SCHEMA:public}
    username: ${DB_USER:crediya}
    password: ${DB_PASSWORD:crediya}